name: kidsflutter_app
description: "A kids app flutter project."
flutter_version: 3.35.4

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get: 4.7.2
  ferry: 0.16.1+2
  firebase_crashlytics: 5.0.2
  firebase_core: 4.1.1
  firebase_messaging: 16.0.2
  get_secure_storage: 1.0.5
  fluttertoast: 9.0.0
  lottie: 3.3.2
  connectivity_plus: 7.0.0
  intl: 0.20.2
  flutter_svg: 2.2.1
  gql_http_link: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer:
  ferry_generator:
  build_runner:

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - res/drawable/

